"use client";

import { useState } from "react";

type Proposal = { proposalId: string; factKind: string; oldValue: string | null; newValue: string; conditions: string[]; exceptions: string[] };
export function ProfileCorrectionChat({ roomId, participantId, onConfirmed }: { roomId: string; participantId: string; onConfirmed?: () => void }) {
  const [message, setMessage] = useState(""); const [proposal, setProposal] = useState<Proposal | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function propose(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`/api/profiles/${participantId}/chat`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ roomId, userExplanation: message }) }); if (!response.ok) throw new Error("제안을 만들지 못했어요."); setProposal(await response.json()); } catch (caught) { setError(caught instanceof Error ? caught.message : "제안을 만들지 못했어요."); } finally { setBusy(false); } }
  async function confirm() { if (!proposal) return; setBusy(true); setError(""); try { const response = await fetch(`/api/profiles/${participantId}/chat`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ roomId, proposalId: proposal.proposalId }) }); if (!response.ok) throw new Error("반영하지 못했어요."); setProposal(null); setMessage(""); onConfirmed?.(); } catch (caught) { setError(caught instanceof Error ? caught.message : "반영하지 못했어요."); } finally { setBusy(false); } }
  return <section className="correction-chat" aria-labelledby="correction-title"><p className="eyebrow">AI와 교정</p><h2 id="correction-title">말로 설명해서 고치기</h2><p className="muted">바로 저장하지 않아요. 반영할 내용을 먼저 확인해 주세요.</p><form onSubmit={propose}><label className="sr-only" htmlFor="correction-message">교정 설명</label><textarea id="correction-message" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="예: 민수는 친한 사람에게만 저렇게 말해" required rows={3} /><button className="secondary-button" disabled={busy}>{busy ? "제안 만드는 중…" : "수정 제안 받기"}</button></form>{proposal && <div className="proposal" role="status"><p><b>{proposal.oldValue ?? "새 항목"}</b> → <b>{proposal.newValue}</b></p><p className="muted">조건: {proposal.conditions.join(", ") || "없음"} · 예외: {proposal.exceptions.join(", ") || "없음"}</p><div><button type="button" className="secondary-button" onClick={() => setProposal(null)}>취소</button><button type="button" className="primary-button" onClick={confirm} disabled={busy}>이 내용으로 반영</button></div></div>}{error && <p className="form-error" role="alert">{error}</p>}</section>;
}
