"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { BottomNav } from "./bottom-nav";
import { ImportProgress } from "./import-progress";
import { RoomCard } from "./room-card";
import type { RoomView } from "@/domain/rooms/room-read-types";
type Review = { roomId: string; unparsedLines: Array<{ line: number; text: string }> };

export function RoomsWorkspace({ initialRooms }: { initialRooms: RoomView[] }) {
  const router = useRouter(); const [file, setFile] = useState<File | null>(null); const [selfName, setSelfName] = useState(""); const [existingRoomId, setExistingRoomId] = useState(""); const [progress, setProgress] = useState<number | null>(null); const [summary, setSummary] = useState<Review | null>(null); const [error, setError] = useState(""); const [analyzing, setAnalyzing] = useState(false);
  useEffect(() => { const roomId = sessionStorage.getItem("import-review-room"); const raw = roomId && sessionStorage.getItem(`import-review:${roomId}`); if (!raw) return; try { setSummary(JSON.parse(raw)); setProgress(100); } catch { sessionStorage.removeItem("import-review-room"); } }, []);
  async function upload(event: React.FormEvent) { event.preventDefault(); if (!file || !selfName.trim()) return; setError(""); setProgress(20); try { const form = new FormData(); form.append("file", file); form.append("selfName", selfName); if (existingRoomId) form.append("existingRoomId", existingRoomId); const response = await fetch("/api/imports", { method: "POST", body: form }); if (!response.ok) throw new Error("대화를 가져오지 못했어요. 카카오톡 .txt 또는 .csv 파일과 내 이름을 다시 확인해 주세요."); const data = await response.json(); const review = { roomId: data.roomId, unparsedLines: data.unparsedLines ?? [] }; sessionStorage.setItem("import-review-room", review.roomId); sessionStorage.setItem(`import-review:${review.roomId}`, JSON.stringify(review)); setSummary(review); setProgress(100); } catch (caught) { setProgress(null); setError(caught instanceof Error ? caught.message : "대화를 가져오지 못했어요."); } }
  function analyze() { if (!summary || analyzing) return; setAnalyzing(true); setError(""); sessionStorage.removeItem(`import-review:${summary.roomId}`); sessionStorage.removeItem("import-review-room"); void fetch(`/api/rooms/${summary.roomId}/analysis`, { method: "POST" }).catch(() => undefined); router.push(`/rooms/${summary.roomId}`); router.refresh(); }
  return <main className="mobile-page"><header className="hero"><p className="eyebrow">나만의 답장 도우미</p><h1>대화의 결을<br />놓치지 않게.</h1><p>카카오톡 대화를 안전하게 정리하고, 지금에 맞는 답장을 함께 골라요.</p></header><section className="upload-panel"><h2>카카오톡 파일 가져오기</h2><form onSubmit={upload}><label className="file-picker"><input type="file" accept=".txt,.csv,text/plain,text/csv" aria-label="카카오톡 파일 업로드" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><span>{file ? file.name : "카카오톡 .txt 또는 .csv 파일 선택"}</span><small>파일 선택</small></label><label>가져올 대화방<select aria-label="가져올 대화방" value={existingRoomId} onChange={(event) => setExistingRoomId(event.target.value)}><option value="">새 대화방 만들기</option>{initialRooms.map((room) => <option value={room.id} key={room.id}>{room.title}에 추가</option>)}</select></label><label>내 이름<input aria-label="내 이름" value={selfName} onChange={(event) => setSelfName(event.target.value)} required /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-button" disabled={!file || !selfName || progress !== null}>파일 가져오기</button></form></section>{progress !== null && <ImportProgress progress={progress} unparsedLines={summary?.unparsedLines} />}{summary && <section className="upload-panel"><h2>가져오기 검토</h2><p className="muted">확인할 줄을 검토한 뒤 분석을 시작해 주세요.</p><button type="button" className="primary-button" disabled={analyzing} onClick={analyze}>{analyzing ? "분석 중…" : "검토 후 분석 시작"}</button></section>}<section className="room-list"><h2>다시 이어갈 대화</h2>{initialRooms.map((room) => <RoomCard room={{ id: room.id, title: room.title, status: room.analysisStatus === "ready" ? "ready" : "needs_review", updatedAt: new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium" }).format(new Date(room.updatedAt)), participantCount: room.participants.length }} key={room.id} />)}</section><BottomNav /></main>;
}
