"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { BottomNav } from "./bottom-nav";
import { ImportProgress } from "./import-progress";
import { RoomCard } from "./room-card";
import type { RoomView } from "@/domain/rooms/room-read-types";

export function RoomsWorkspace({ initialRooms }: { initialRooms: RoomView[] }) {
  const router = useRouter(); const [file, setFile] = useState<File | null>(null); const [selfName, setSelfName] = useState(""); const [progress, setProgress] = useState<number | null>(null); const [error, setError] = useState("");
  async function upload(event: React.FormEvent) { event.preventDefault(); if (!file || !selfName.trim()) return; setError(""); setProgress(25); try { const form = new FormData(); form.append("file", file); form.append("selfName", selfName); const response = await fetch("/api/imports", { method: "POST", body: form }); if (!response.ok) throw new Error("대화를 가져오지 못했어요. .txt 파일과 내 이름을 다시 확인해 주세요."); const summary = await response.json(); setProgress(100); router.push(`/rooms/${summary.roomId}`); } catch (caught) { setProgress(null); setError(caught instanceof Error ? caught.message : "대화를 가져오지 못했어요."); } }
  return <main className="mobile-page"><header className="hero"><p className="eyebrow">나만의 답장 도우미</p><h1>대화의 결을<br />놓치지 않게.</h1><p>카카오톡 대화를 안전하게 정리하고, 지금에 맞는 답장을 함께 골라요.</p></header><section className="upload-panel" aria-labelledby="upload-title"><div className="section-heading"><div><p className="eyebrow">새 대화방</p><h2 id="upload-title">카카오톡 파일 가져오기</h2></div><span aria-hidden="true" className="spark">✦</span></div><form onSubmit={upload}><label className="file-picker"><input type="file" accept=".txt,text/plain" aria-label="카카오톡 파일 업로드" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><span>{file ? file.name : "카카오톡 .txt 파일 선택"}</span><small>파일 선택</small></label><label>내 이름<input aria-label="내 이름" value={selfName} onChange={(event) => setSelfName(event.target.value)} placeholder="대화에 표시된 내 이름" required /></label><p className="privacy-copy">원문은 암호화해 저장하며, 답장에 필요한 범위만 분석해요.</p>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-button" disabled={!file || !selfName || progress !== null}>분석 시작하기</button></form></section>{progress !== null && <ImportProgress progress={progress} />}<section className="room-list" aria-labelledby="room-list-title"><div className="section-heading"><div><p className="eyebrow">내 대화방</p><h2 id="room-list-title">다시 이어갈 대화</h2></div><span className="room-count">{initialRooms.length}</span></div>{initialRooms.length ? initialRooms.map((room) => <RoomCard room={{ id: room.id, title: room.title, status: "ready", updatedAt: new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium" }).format(new Date(room.updatedAt)), participantCount: room.participants.length }} key={room.id} />) : <div className="empty-state"><span aria-hidden="true">☁</span><h3>아직 대화방이 없어요</h3><p>카카오톡 내보내기 파일을 올리면 이곳에서 분석과 검수를 이어갈 수 있어요.</p></div>}</section><BottomNav /></main>;
}
